# Generated by Django 5.2.8 on 2025-11-26 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sae', '0002_saerun_sparsity_heatmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAEFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_index', models.IntegerField(db_index=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('density', models.FloatField(help_text='Frequenza di attivazione nel dataset', null=True)),
                ('max_activation', models.FloatField(help_text='Massima attivazione registrata', null=True)),
                ('example_docs', models.JSONField(blank=True, default=list)),
                ('confidence_score', models.FloatField(blank=True, help_text='Score del Predictor (futuro)', null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='sae.saerun')),
            ],
            options={
                'ordering': ['-density'],
                'unique_together': {('run', 'feature_index')},
            },
        ),
    ]
