# Generated by Django 5.2.8 on 2025-11-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saefeature',
            options={'ordering': ['-max_activation']},
        ),
        migrations.RemoveField(
            model_name='saefeature',
            name='confidence_score',
        ),
        migrations.AddField(
            model_name='saefeature',
            name='activation_histogram',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='saefeature',
            name='co_occurring_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='saefeature',
            name='correlated_features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='saefeature',
            name='density',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='saefeature',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='saefeature',
            name='label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='saefeature',
            name='max_activation',
            field=models.FloatField(null=True),
        ),
    ]
