# Generated by Django 5.2.8 on 2025-11-27 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0003_interpretation_saefeature_active_interpretation'),
        ('sae', '0002_saerun_sparsity_heatmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iteration', models.IntegerField(default=0, help_text="Iterazione dell'algoritmo in cui è stata trovata")),
                ('size', models.IntegerField(default=0)),
                ('family_label', models.CharField(blank=True, help_text='Etichetta riassuntiva della famiglia', max_length=255)),
                ('children_features', models.ManyToManyField(related_name='family_children', to='explorer.saefeature')),
                ('parent_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_parent', to='explorer.saefeature')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='families', to='sae.saerun')),
            ],
            options={
                'ordering': ['iteration', '-size'],
            },
        ),
    ]
