# Generated by Django 5.2.7 on 2025-12-03 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0004_featurefamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='saefeature',
            name='mean_activation',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='saefeature',
            name='variance_activation',
            field=models.FloatField(null=True),
        ),
    ]
