# Generated by Django 6.0.3 on 2026-03-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0005_saefeature_mean_activation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.TextField(default='')),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
