# Generated by Django 6.0.3 on 2026-04-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0006_appsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='interpretation',
            name='predictor_f1',
            field=models.FloatField(blank=True, help_text='F1 score of binary activation prediction', null=True),
        ),
        migrations.AddField(
            model_name='interpretation',
            name='predictor_pearson',
            field=models.FloatField(blank=True, help_text='Pearson correlation between predicted and actual activations', null=True),
        ),
    ]
