# Generated by Django 5.2.7 on 2025-11-26 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('embeddings', '0002_dataset_document_delete_uploadedjson'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAERun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_dim', models.IntegerField(help_text='Input embedding dimension (e.g. 768)')),
                ('expansion_factor', models.IntegerField(default=4, help_text='Latent expansion factor (e.g. 4x)')),
                ('k_sparsity', models.IntegerField(default=32, help_text='Top-K active neurons')),
                ('alpha_aux', models.FloatField(default=0.03, help_text='Auxiliary Loss Coefficient')),
                ('learning_rate', models.FloatField(default=0.0001)),
                ('batch_size', models.IntegerField(default=512)),
                ('epochs', models.IntegerField(default=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Training'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('weights_file', models.FileField(blank=True, null=True, upload_to='sae_weights/')),
                ('final_loss', models.FloatField(blank=True, null=True)),
                ('training_log', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sae_runs', to='embeddings.dataset')),
            ],
        ),
    ]
