# Generated by Django 5.2.8 on 2025-11-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sae', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saerun',
            name='sparsity_heatmap',
            field=models.ImageField(blank=True, null=True, upload_to='sae_plots/'),
        ),
    ]
