# Generated by Django 5.2.7 on 2025-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sae', '0002_saerun_sparsity_heatmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='saerun',
            name='matrix_c_heatmap',
            field=models.ImageField(blank=True, help_text='Co-occurrence Matrix', null=True, upload_to='sae_plots/'),
        ),
        migrations.AddField(
            model_name='saerun',
            name='matrix_d_heatmap',
            field=models.ImageField(blank=True, help_text='Dense Activation Similarity Matrix', null=True, upload_to='sae_plots/'),
        ),
        migrations.AddField(
            model_name='saerun',
            name='matrix_s_heatmap',
            field=models.ImageField(blank=True, help_text='Similarity Matrix (Decoder Weights)', null=True, upload_to='sae_plots/'),
        ),
    ]
