# Generated by Django 6.0.3 on 2026-04-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sae', '0003_saerun_matrix_c_heatmap_saerun_matrix_d_heatmap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saerun',
            name='alpha_aux',
            field=models.FloatField(default=0.03125, help_text='Auxiliary Loss Coefficient (paper: 1/32)'),
        ),
        migrations.AlterField(
            model_name='saerun',
            name='batch_size',
            field=models.IntegerField(default=1024, help_text='Paper: 1024'),
        ),
    ]
