# Generated by Django 5.2.8 on 2026-04-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sae', '0004_alter_saerun_alpha_aux_alter_saerun_batch_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='saerun',
            name='dead_neuron_ratio',
            field=models.FloatField(blank=True, help_text='Fraction of latent neurons that never activate', null=True),
        ),
        migrations.AddField(
            model_name='saerun',
            name='mean_l0',
            field=models.FloatField(blank=True, help_text='Average number of active features per input', null=True),
        ),
        migrations.AddField(
            model_name='saerun',
            name='sparsity_index',
            field=models.FloatField(blank=True, help_text='1 - mean_l0/d_latent, normalized [0,1]', null=True),
        ),
    ]
