# Generated by Django 5.2.8 on 2026-03-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0005_remove_dataset_analysis_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='opensearch_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='model_name',
            field=models.CharField(choices=[('medbit', 'IVN-RIN/medBIT'), ('bio_bert_sentence', 'pritamdeka/Sentence-BioBERT'), ('sapbert', 'cambridgeltl/SapBERT-from-PubMedBERT-fulltext'), ('sbert_multi_minilm', 'sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2'), ('sbert_multi_distiluse', 'sentence-transformers/distiluse-base-multilingual-cased-v2'), ('gte_base', 'thenlper/gte-base'), ('gte_large', 'thenlper/gte-large'), ('gte_multilingual', 'Alibaba-NLP/gte-multilingual-base'), ('sbert_mpnet', 'sentence-transformers/all-mpnet-base-v2'), ('sbert_minilm', 'sentence-transformers/all-MiniLM-L6-v2')], default='medbit', max_length=100),
        ),
    ]
