# Generated by Django 5.2.8 on 2026-03-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0006_add_opensearch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='model_name',
            field=models.CharField(default='nomic-embed-text:latest', max_length=200),
        ),
    ]
