# Generated by Django 6.0.3 on 2026-04-03 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0007_ollama_model_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='opensearch_id',
        ),
    ]
