# Generated by Django 5.2.8 on 2026-04-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('embeddings', '0008_remove_opensearch_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='embedding',
        ),
    ]
